=== suxiaohei/Ladder/Ladder/doc/schema/bcmQ.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="bcm">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="class" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="data-property" nillable="false" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="dp" maxOccurs="unbounded">
											<xs:complexType>
												<xs:attribute name="field" type="xs:string" use="required"/>
												<xs:attribute name="showName" type="xs:string"/>
												<xs:attribute name="advance" type="xs:boolean" default="false"/>
												<xs:attribute name="sort" type="xs:integer" default="0"/>
												<xs:attribute name="chart" type="xs:string" default="pie"/>
												<xs:attribute name="hidden" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="object-property" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="op" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="rel-dp" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute name="field" type="xs:string" use="required"/>
															<xs:attribute name="showName" type="xs:string"/>
															<xs:attribute name="advance" type="xs:boolean" default="false"/>
															<xs:attribute name="sort" type="xs:integer" default="0"/>
															<xs:attribute name="chart" type="xs:string" default="pie"/>
															<xs:attribute name="hidden" type="xs:boolean" default="false"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="field" type="xs:string" use="required"/>
												<xs:attribute name="showName" type="xs:string"/>
												<xs:attribute name="image" type="xs:string"/>
												<xs:attribute name="advance" type="xs:boolean" default="false"/>
												<xs:attribute name="sort" type="xs:integer" default="0"/>
												<xs:attribute name="chart" type="xs:string" default="pie"/>
												<xs:attribute name="hidden" type="xs:boolean" default="false"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="field" type="xs:string" use="required"/>
						<xs:attribute name="showName" type="xs:string"/>
						<xs:attribute name="sort" type="xs:integer" default="0"/>
						<xs:attribute name="image" type="xs:string"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="import">
					<xs:complexType>
						<xs:attribute name="resource" type="xs:string"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="required"/>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="owl"/>
						<xs:enumeration value="web"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="owlVersion" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== suxiaohei/Ladder/Ladder/doc/schema/bcmQ.xml
<?xml version="1.0" encoding="UTF-8"?>
<bcm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="bcmQ.xsd"
	version="5.0" type="web" owlVersion="5.0">
	<class field="JournalPaper" sort="1" image="default.jpg">
		<data-property>
			<dp field="title" sort="1" chart="pie" advance="true" />
			<dp field="otherTitle" showName="第二标题"/>
			<dp field="issn"/>
			<dp field="abstract" sort="2" advance="true"/>
			<dp field="year" />
			<dp field="volume"/>
			<dp field="issue"/>
			<dp field="startPage"/>
			<dp field="endPage"/>
			<dp field="createTime" hidden="true"/>
		</data-property>
		<object-property>
			<op field="hasOrganization" showName="单位"
			sort="1" image="default.jpg" advance="true">
			<rel-dp field="name" />
			</op>
			<op field="hasAuthor" showName="作者">
				<rel-dp field="sequence" hidden="true"/>
				<rel-dp field="name" chart="pie" showName="作者"
				sort="1" advance="true"/>
			</op>
			<op field="hasPublisher" showName="发布者" hidden="true">
				<rel-dp field="name" />
			</op>
			<op field="hasKeyword" showName="关键词" >
				<rel-dp field="name" />
				<rel-dp field="weight" />
			</op>
		</object-property>
	</class>
	<class field="People" showName="作者" >
		<data-property>
			<dp field="sequence"/>
			<dp field="name"/>
			<dp field="birthday"/>
		</data-property>
		<object-property>
			<op field="hasOrganization" >
				<rel-dp field="name"/>
			</op>
		</object-property>
	</class>
	<class field="Organization" showName="单位">
		<data-property>
			<dp field="name"/>
			<dp field="address"/>
			<dp field="city"/>
		</data-property>
	</class>
	<!-- 引入其它配置文件-->
	<import resource="bcm-degree.xml"/>
</bcm>
